import {
  Workflow,
  WorkflowExecution,
  Integration,
  WorkflowTemplate,
  DashboardStats,
  User,
  Project,
  ProjectMember,
  ProjectRole,
  WorkflowNode,
  WorkflowEdge,
} from './types'

// Mock Users
export const mockUsers: User[] = [
  {
    id: 'user-1',
    email: 'john.doe@example.com',
    name: 'John Doe',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'user-2',
    email: 'jane.smith@example.com',
    name: 'Jane Smith',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: 'user-3',
    email: 'bob.wilson@example.com',
    name: 'Bob Wilson',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-01'),
  },
  {
    id: 'user-4',
    email: 'alice.brown@example.com',
    name: 'Alice Brown',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-03-10'),
  },
]

// Mock Projects
export const mockProjects: Project[] = [
  {
    id: 'project-1',
    name: 'Marketing Automation',
    description: 'Automate marketing workflows and campaigns',
    ownerId: 'user-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-10'),
    memberCount: 3,
    workflowCount: 3,
  },
  {
    id: 'project-2',
    name: 'Sales Operations',
    description: 'Lead management and sales process automation',
    ownerId: 'user-2',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-09'),
    memberCount: 2,
    workflowCount: 2,
  },
  {
    id: 'project-3',
    name: 'Customer Support',
    description: 'Support ticket automation and follow-ups',
    ownerId: 'user-1',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-08'),
    memberCount: 4,
    workflowCount: 1,
  },
]

// Mock Project Members
export const mockProjectMembers: ProjectMember[] = [
  // Marketing Automation project
  {
    id: 'member-1',
    userId: 'user-1',
    projectId: 'project-1',
    role: 'PROJECT_OWNER',
    invitedBy: 'user-1',
    invitedAt: new Date('2024-01-15'),
    joinedAt: new Date('2024-01-15'),
    user: mockUsers[0],
  },
  {
    id: 'member-2',
    userId: 'user-2',
    projectId: 'project-1',
    role: 'WORKFLOW_BUILDER',
    invitedBy: 'user-1',
    invitedAt: new Date('2024-01-16'),
    joinedAt: new Date('2024-01-16'),
    user: mockUsers[1],
  },
  {
    id: 'member-3',
    userId: 'user-3',
    projectId: 'project-1',
    role: 'WORKFLOW_RUNNER',
    invitedBy: 'user-1',
    invitedAt: new Date('2024-01-17'),
    joinedAt: new Date('2024-01-17'),
    user: mockUsers[2],
  },
  // Sales Operations project
  {
    id: 'member-4',
    userId: 'user-2',
    projectId: 'project-2',
    role: 'PROJECT_OWNER',
    invitedBy: 'user-2',
    invitedAt: new Date('2024-02-01'),
    joinedAt: new Date('2024-02-01'),
    user: mockUsers[1],
  },
  {
    id: 'member-5',
    userId: 'user-4',
    projectId: 'project-2',
    role: 'PROJECT_ADMIN',
    invitedBy: 'user-2',
    invitedAt: new Date('2024-02-02'),
    joinedAt: new Date('2024-02-02'),
    user: mockUsers[3],
  },
  // Customer Support project
  {
    id: 'member-6',
    userId: 'user-1',
    projectId: 'project-3',
    role: 'PROJECT_OWNER',
    invitedBy: 'user-1',
    invitedAt: new Date('2024-01-20'),
    joinedAt: new Date('2024-01-20'),
    user: mockUsers[0],
  },
  {
    id: 'member-7',
    userId: 'user-3',
    projectId: 'project-3',
    role: 'WORKFLOW_BUILDER',
    invitedBy: 'user-1',
    invitedAt: new Date('2024-01-21'),
    joinedAt: new Date('2024-01-21'),
    user: mockUsers[2],
  },
  {
    id: 'member-8',
    userId: 'user-4',
    projectId: 'project-3',
    role: 'VIEWER',
    invitedBy: 'user-1',
    invitedAt: new Date('2024-01-22'),
    joinedAt: new Date('2024-01-22'),
    user: mockUsers[3],
  },
  {
    id: 'member-9',
    userId: 'user-2',
    projectId: 'project-3',
    role: 'WORKFLOW_RUNNER',
    invitedBy: 'user-1',
    invitedAt: new Date('2024-01-23'),
    joinedAt: new Date('2024-01-23'),
    user: mockUsers[1],
  },
]

export const mockWorkflows: Workflow[] = [
  {
    id: '1',
    projectId: 'project-1',
    name: 'Slack Notification on New Email',
    description: 'Send Slack message when new email arrives in Gmail',
    status: 'active',
    nodes: [],
    edges: [],
    createdBy: 'user-1',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-10'),
    executions: 1542,
    successRate: 98.5,
    lastRun: new Date(Date.now() - 5 * 60000), // 5 min ago
  },
  {
    id: '2',
    projectId: 'project-1',
    name: 'Notion Database Sync',
    description: 'Sync completed tasks from Asana to Notion database',
    status: 'active',
    nodes: [],
    edges: [],
    createdBy: 'user-2',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-09'),
    executions: 847,
    successRate: 99.2,
    lastRun: new Date(Date.now() - 30 * 60000),
  },
  {
    id: '3',
    projectId: 'project-2',
    name: 'Lead Scoring',
    description: 'Score leads from Google Forms and send to CRM',
    status: 'active',
    nodes: [],
    edges: [],
    createdBy: 'user-2',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-08'),
    executions: 2103,
    successRate: 97.1,
    lastRun: new Date(Date.now() - 2 * 60000),
  },
  {
    id: '4',
    projectId: 'project-2',
    name: 'Daily Digest Report',
    description: 'Compile daily stats and email report',
    status: 'inactive',
    nodes: [],
    edges: [],
    createdBy: 'user-4',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-05'),
    executions: 45,
    successRate: 100,
  },
  {
    id: '5',
    projectId: 'project-3',
    name: 'Stripe Payment Processing',
    description: 'Create invoice in accounting software on Stripe payment',
    status: 'active',
    nodes: [],
    edges: [],
    createdBy: 'user-1',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-03-11'),
    executions: 5643,
    successRate: 99.8,
    lastRun: new Date(Date.now() - 1 * 60000),
  },
  {
    id: '6',
    projectId: 'project-1',
    name: 'Social Media Posting',
    description: 'Auto-post to Twitter, LinkedIn, and Facebook from buffer',
    status: 'draft',
    nodes: [],
    edges: [],
    createdBy: 'user-2',
    createdAt: new Date('2024-03-12'),
    updatedAt: new Date('2024-03-12'),
    executions: 0,
    successRate: 0,
  },
]

export const mockExecutions: WorkflowExecution[] = [
  {
    id: 'exec-1',
    workflowId: '1',
    projectId: 'project-1',
    workflowName: 'Slack Notification on New Email',
    status: 'success',
    startedAt: new Date(Date.now() - 2 * 60000),
    completedAt: new Date(Date.now() - 1 * 60000),
    duration: 1240,
    triggeredBy: 'user-3',
  },
  {
    id: 'exec-2',
    workflowId: '3',
    projectId: 'project-2',
    workflowName: 'Lead Scoring',
    status: 'success',
    startedAt: new Date(Date.now() - 5 * 60000),
    completedAt: new Date(Date.now() - 4 * 60000),
    duration: 3450,
    triggeredBy: 'user-4',
  },
  {
    id: 'exec-3',
    workflowId: '2',
    projectId: 'project-1',
    workflowName: 'Notion Database Sync',
    status: 'running',
    startedAt: new Date(Date.now() - 30 * 1000),
    duration: 30000,
    triggeredBy: 'user-2',
  },
  {
    id: 'exec-4',
    workflowId: '5',
    projectId: 'project-3',
    workflowName: 'Stripe Payment Processing',
    status: 'success',
    startedAt: new Date(Date.now() - 15 * 60000),
    completedAt: new Date(Date.now() - 14 * 60000),
    duration: 2150,
    triggeredBy: 'user-1',
  },
  {
    id: 'exec-5',
    workflowId: '1',
    projectId: 'project-1',
    workflowName: 'Slack Notification on New Email',
    status: 'failed',
    startedAt: new Date(Date.now() - 25 * 60000),
    completedAt: new Date(Date.now() - 24 * 60000),
    duration: 5000,
    error: 'Slack API timeout',
    triggeredBy: 'user-3',
  },
  {
    id: 'exec-6',
    workflowId: '3',
    projectId: 'project-2',
    workflowName: 'Lead Scoring',
    status: 'success',
    startedAt: new Date(Date.now() - 1 * 3600000),
    completedAt: new Date(Date.now() - 1 * 3600000 + 2500),
    duration: 2500,
    triggeredBy: 'user-2',
  },
  {
    id: 'exec-7',
    workflowId: '5',
    projectId: 'project-3',
    workflowName: 'Stripe Payment Processing',
    status: 'success',
    startedAt: new Date(Date.now() - 2 * 3600000),
    completedAt: new Date(Date.now() - 2 * 3600000 + 1800),
    duration: 1800,
    triggeredBy: 'user-1',
  },
  {
    id: 'exec-8',
    workflowId: '2',
    projectId: 'project-1',
    workflowName: 'Notion Database Sync',
    status: 'success',
    startedAt: new Date(Date.now() - 3 * 3600000),
    completedAt: new Date(Date.now() - 3 * 3600000 + 4200),
    duration: 4200,
    triggeredBy: 'user-2',
  },
]

export const mockIntegrations: Integration[] = [
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages and manage channels',
    icon: '💬',
    category: 'Communication',
    connected: true,
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Send emails and manage inbox',
    icon: '✉️',
    category: 'Email',
    connected: true,
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Create and update database items',
    icon: '📝',
    category: 'Productivity',
    connected: true,
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Monitor payments and transactions',
    icon: '💳',
    category: 'Payments',
    connected: false,
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Read and write spreadsheet data',
    icon: '📊',
    category: 'Productivity',
    connected: false,
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Send messages and manage servers',
    icon: '👾',
    category: 'Communication',
    connected: false,
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Create and update tasks and projects',
    icon: '✓',
    category: 'Project Management',
    connected: false,
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Manage repositories and issues',
    icon: '🐙',
    category: 'Development',
    connected: false,
  },
]

export const mockTemplates: WorkflowTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Daily Standup Reminder',
    description: 'Send daily standup reminder to Slack at 9 AM',
    apps: ['Slack', 'Schedule'],
    category: 'Communication',
    installs: 1240,
    rating: 4.8,
  },
  {
    id: 'tmpl-2',
    name: 'Lead to CRM',
    description: 'Automatically add form submissions to your CRM',
    apps: ['Google Forms', 'HubSpot', 'Slack'],
    category: 'Sales',
    installs: 3450,
    rating: 4.9,
  },
  {
    id: 'tmpl-3',
    name: 'Backup Notion to Google Drive',
    description: 'Automatically backup Notion databases to Google Drive',
    apps: ['Notion', 'Google Drive'],
    category: 'Backup',
    installs: 892,
    rating: 4.6,
  },
  {
    id: 'tmpl-4',
    name: 'Social Media Share',
    description: 'Share new blog posts to social media automatically',
    apps: ['RSS', 'Twitter', 'LinkedIn', 'Facebook'],
    category: 'Marketing',
    installs: 2156,
    rating: 4.7,
  },
  {
    id: 'tmpl-5',
    name: 'Customer Survey Follow-up',
    description: 'Send follow-up email based on survey responses',
    apps: ['Typeform', 'Gmail', 'Stripe'],
    category: 'Customer Success',
    installs: 567,
    rating: 4.4,
  },
  {
    id: 'tmpl-6',
    name: 'Expense Report Automation',
    description: 'Convert receipt emails to expense reports',
    apps: ['Gmail', 'Google Sheets', 'Expensify'],
    category: 'Finance',
    installs: 1834,
    rating: 4.5,
  },
  {
    id: 'tmpl-7',
    name: 'Discord Notifications',
    description: 'Send important alerts to Discord channel',
    apps: ['Webhook', 'Discord', 'Monitoring'],
    category: 'Alerts',
    installs: 4521,
    rating: 4.8,
  },
  {
    id: 'tmpl-8',
    name: 'Salesforce to Slack',
    description: 'Post new Salesforce opportunities to Slack',
    apps: ['Salesforce', 'Slack'],
    category: 'Sales',
    installs: 2143,
    rating: 4.6,
  },
]

export const mockDashboardStats: DashboardStats = {
  totalWorkflows: mockWorkflows.length,
  activeWorkflows: mockWorkflows.filter((w) => w.status === 'active').length,
  totalExecutions: mockExecutions.length,
  successRate: 98.5,
}
