import {
  Workflow,
  WorkflowExecution,
  Integration,
  WorkflowTemplate,
  DashboardStats,
} from './types'

export const mockWorkflows: Workflow[] = [
  {
    id: '1',
    name: 'Slack Notification on New Email',
    description: 'Send Slack message when new email arrives in Gmail',
    status: 'active',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-03-10'),
    executions: 1542,
    successRate: 98.5,
    lastRun: new Date(Date.now() - 5 * 60000), // 5 min ago
  },
  {
    id: '2',
    name: 'Notion Database Sync',
    description: 'Sync completed tasks from Asana to Notion database',
    status: 'active',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-03-09'),
    executions: 847,
    successRate: 99.2,
    lastRun: new Date(Date.now() - 30 * 60000),
  },
  {
    id: '3',
    name: 'Lead Scoring',
    description: 'Score leads from Google Forms and send to CRM',
    status: 'active',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-03-08'),
    executions: 2103,
    successRate: 97.1,
    lastRun: new Date(Date.now() - 2 * 60000),
  },
  {
    id: '4',
    name: 'Daily Digest Report',
    description: 'Compile daily stats and email report',
    status: 'inactive',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-03-05'),
    executions: 45,
    successRate: 100,
  },
  {
    id: '5',
    name: 'Stripe Payment Processing',
    description: 'Create invoice in accounting software on Stripe payment',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-03-11'),
    executions: 5643,
    successRate: 99.8,
    lastRun: new Date(Date.now() - 1 * 60000),
  },
  {
    id: '6',
    name: 'Social Media Posting',
    description: 'Auto-post to Twitter, LinkedIn, and Facebook from buffer',
    status: 'draft',
    createdAt: new Date('2024-03-12'),
    updatedAt: new Date('2024-03-12'),
    executions: 0,
    successRate: 0,
  },
]

export const mockExecutions: WorkflowExecution[] = [
  {
    id: 'exec-1',
    workflowId: '1',
    workflowName: 'Slack Notification on New Email',
    status: 'success',
    startedAt: new Date(Date.now() - 2 * 60000),
    completedAt: new Date(Date.now() - 1 * 60000),
    duration: 1240,
  },
  {
    id: 'exec-2',
    workflowId: '3',
    workflowName: 'Lead Scoring',
    status: 'success',
    startedAt: new Date(Date.now() - 5 * 60000),
    completedAt: new Date(Date.now() - 4 * 60000),
    duration: 3450,
  },
  {
    id: 'exec-3',
    workflowId: '2',
    workflowName: 'Notion Database Sync',
    status: 'running',
    startedAt: new Date(Date.now() - 30 * 1000),
    duration: 30000,
  },
  {
    id: 'exec-4',
    workflowId: '5',
    workflowName: 'Stripe Payment Processing',
    status: 'success',
    startedAt: new Date(Date.now() - 15 * 60000),
    completedAt: new Date(Date.now() - 14 * 60000),
    duration: 2150,
  },
  {
    id: 'exec-5',
    workflowId: '1',
    workflowName: 'Slack Notification on New Email',
    status: 'failed',
    startedAt: new Date(Date.now() - 25 * 60000),
    completedAt: new Date(Date.now() - 24 * 60000),
    duration: 5000,
    error: 'Slack API timeout',
  },
  {
    id: 'exec-6',
    workflowId: '3',
    workflowName: 'Lead Scoring',
    status: 'success',
    startedAt: new Date(Date.now() - 1 * 3600000),
    completedAt: new Date(Date.now() - 1 * 3600000 + 2500),
    duration: 2500,
  },
  {
    id: 'exec-7',
    workflowId: '5',
    workflowName: 'Stripe Payment Processing',
    status: 'success',
    startedAt: new Date(Date.now() - 2 * 3600000),
    completedAt: new Date(Date.now() - 2 * 3600000 + 1800),
    duration: 1800,
  },
  {
    id: 'exec-8',
    workflowId: '2',
    workflowName: 'Notion Database Sync',
    status: 'success',
    startedAt: new Date(Date.now() - 3 * 3600000),
    completedAt: new Date(Date.now() - 3 * 3600000 + 4200),
    duration: 4200,
  },
]

export const mockIntegrations: Integration[] = [
  {
    id: 'slack',
    name: 'Slack',
    description: 'Send messages and manage channels',
    icon: '💬',
    category: 'Communication',
    connected: true,
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Send emails and manage inbox',
    icon: '✉️',
    category: 'Email',
    connected: true,
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'Create and update database items',
    icon: '📝',
    category: 'Productivity',
    connected: true,
  },
  {
    id: 'stripe',
    name: 'Stripe',
    description: 'Monitor payments and transactions',
    icon: '💳',
    category: 'Payments',
    connected: false,
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Read and write spreadsheet data',
    icon: '📊',
    category: 'Productivity',
    connected: false,
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Send messages and manage servers',
    icon: '👾',
    category: 'Communication',
    connected: false,
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Create and update tasks and projects',
    icon: '✓',
    category: 'Project Management',
    connected: false,
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Manage repositories and issues',
    icon: '🐙',
    category: 'Development',
    connected: false,
  },
]

export const mockTemplates: WorkflowTemplate[] = [
  {
    id: 'tmpl-1',
    name: 'Daily Standup Reminder',
    description: 'Send daily standup reminder to Slack at 9 AM',
    apps: ['Slack', 'Schedule'],
    category: 'Communication',
    installs: 1240,
  },
  {
    id: 'tmpl-2',
    name: 'Lead to CRM',
    description: 'Automatically add form submissions to your CRM',
    apps: ['Google Forms', 'HubSpot', 'Slack'],
    category: 'Sales',
    installs: 3450,
  },
  {
    id: 'tmpl-3',
    name: 'Backup Notion to Google Drive',
    description: 'Automatically backup Notion databases to Google Drive',
    apps: ['Notion', 'Google Drive'],
    category: 'Backup',
    installs: 892,
  },
  {
    id: 'tmpl-4',
    name: 'Social Media Share',
    description: 'Share new blog posts to social media automatically',
    apps: ['RSS', 'Twitter', 'LinkedIn', 'Facebook'],
    category: 'Marketing',
    installs: 2156,
  },
  {
    id: 'tmpl-5',
    name: 'Customer Survey Follow-up',
    description: 'Send follow-up email based on survey responses',
    apps: ['Typeform', 'Gmail', 'Stripe'],
    category: 'Customer Success',
    installs: 567,
  },
  {
    id: 'tmpl-6',
    name: 'Expense Report Automation',
    description: 'Convert receipt emails to expense reports',
    apps: ['Gmail', 'Google Sheets', 'Expensify'],
    category: 'Finance',
    installs: 1834,
  },
  {
    id: 'tmpl-7',
    name: 'Discord Notifications',
    description: 'Send important alerts to Discord channel',
    apps: ['Webhook', 'Discord', 'Monitoring'],
    category: 'Alerts',
    installs: 4521,
  },
  {
    id: 'tmpl-8',
    name: 'Salesforce to Slack',
    description: 'Post new Salesforce opportunities to Slack',
    apps: ['Salesforce', 'Slack'],
    category: 'Sales',
    installs: 2143,
  },
]

export const mockDashboardStats: DashboardStats = {
  totalWorkflows: mockWorkflows.length,
  activeWorkflows: mockWorkflows.filter((w) => w.status === 'active').length,
  totalExecutions: mockExecutions.length,
  successRate: 98.5,
}
